### ISSUE TITLE
call CCRenderTexture's method "clear" 

### ISSUE THREAD

**Issue by gasilu** [cocos2d-x/cocos2dx-win8#4]
hi, call 

rtx->clear(1.0f, 1.0f, 1.0f, 0.0f);

will make a black texture. not a transparent texture.

dev branch.
win8 rc.
vs2012 rc

**Comment by gasilu** [comment]
hi, it seems 
CCEGLView::clearRender() in CCEGLView_win8_metro.cpp, did not initialize the local variable color with its current m_color.
I modified the function like this, and it's ok.

void CCEGLView::clearRender(ID3D11RenderTargetView\* renderTargetView)
{
    float color[4]={m_color[0],m_color[1],m_color[2],m_color[3]};
.....

**Comment by lihex** [comment]
thank you! we will check it soon.

**Comment by lihex** [comment]
fixed in dev brunch now
