### ISSUE TITLE
DirectXRender::m_dwriteFactory - IDWriteFactory1 or IDWriteFactory?

### ISSUE THREAD

**Issue by mingulov** [cocos2d-x/cocos2dx-win8#9]
By DirectXRender.h - m_dwriteFactory should be IDWriteFactory1

https://github.com/cocos2d-x/cocos2dx-win8/blob/master/cocos2dx/platform/win8_metro/DirectXRender.h#L87 :
`Microsoft::WRL::ComPtr<IDWriteFactory1>         m_dwriteFactory;`

But it seems that it is initialized as IDWriteFactory (not IDWriteFactory1)
https://github.com/cocos2d-x/cocos2dx-win8/blob/master/cocos2dx/platform/win8_metro/DirectXRender.cpp#L107 :
__uuidof(IDWriteFactory),

And if specific IDWriteFactory1 methods will be called - there might be some problems.

So I think or m_dwriteFactory should be changed to IDWriteFactory, or it should be initialized as IDWriteFactory.

**Comment by lihex** [comment]
I think you are right. I  changed it to IDWriteFactory1 in dev branch
